name: Test and Deploy CloudFormation Templates
on:
  workflow_call:
    inputs:
      aws_partition:
        description: 'The AWS partition in which the templates will be deployed'
        default: 'aws'
        required: false
        type: string
      job_type:
        description: The type of action being performed on the templates
        required: true
        type: string
      branch_type:
        description: >-
          The type of branch being assessed. Valid values are 'major' (deployment branch)
          or 'minor' (feature branch)
        required: false
        type: string
      github_secret_type:
        description: The type of secret containing the AWS account number (repository, environment, or organization)
        required: false
        type: string
      policy_as_code_provider:
        description: The software used for policy as code validations. Valid values are 'guard' (cfn-guard) or 'opa' (Open Policy Agent)
        required: false
        type: string
      account_number_secret_name:
        description: Name of the GitHub secret containing the AWS account number
        required: false
        type: string
      aws_account_number:
        description: ID number of the target AWS account
        required: false
        type: string
      github_environment:
        description: Name of GitHub environment associated with the target branch
        required: false
        type: string
      github_assumed_role_name:
        description: Path and name of the AWS IAM role assumed by the pipeline. Formatted as PATH/ROLE_NAME
        required: false
        type: string
      config_file_path:
        description: Path to the config file from the root of your GitHub repository
        required: false
        default: 'config'
        type: string
      deployment_folder_path:
        description: Path to the folder containing deployment artifacts
        required: false
        default: 'deployments'
        type: string
      aws_region:
        description: Main AWS region used to assume IAM role
        required: false
        default: 'us-east-1'
        type: string
      rules_repo:
        description: GitHub repo containing your policy as code rules
        required: false
        default: ''
        type: string
      rules_folder_path:
        description: Path to the folder containing your policy as code rules
        required: false
        default: ''
        type: string
    secrets:
      ACCOUNT_NUMBER:
        description: ID number of the target AWS account
        required: false

permissions:
  id-token: write
  contents: write

jobs:
  Perform_Template_Action:
    runs-on: ubuntu-latest
    environment: ${{ inputs.github_environment != '' && inputs.github_environment || null }}
    steps:
      - name: ${{ inputs.job_type }} Templates
        uses: tsamuel33/cloudformation-deployment-action@feature/local-testing
        with:
          job_type: ${{ inputs.job_type }}
          aws_partition: ${{ inputs.aws_partition }}
          branch_type: ${{ inputs.branch_type }}
          github_secret_type: ${{ inputs.github_secret_type }}
          policy_as_code_provider: ${{ inputs.policy_as_code_provider }}
          account_number_secret_name: ${{ inputs.account_number_secret_name }}
          github_environment: ${{ inputs.github_environment }}
          github_assumed_role_name: ${{ inputs.github_assumed_role_name }}
          deployment_folder_path: ${{ inputs.deployment_folder_path }}
          config_file_path: ${{ inputs.config_file_path }}
          aws_account_number: ${{ inputs.github_secret_type != '' && secrets.ACCOUNT_NUMBER || inputs.aws_account_number }}
          rules_repo: ${{ inputs.rules_repo }}
          rules_folder_path: ${{ inputs.rules_folder_path }}
          aws_region: ${{ inputs.aws_region }}